name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build base
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            fangedhex/devcontainers:base
      - name: Build rust
        uses: docker/build-push-action@v2
        with:
          context: rust
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            fangedhex/devcontainers:rust
      - name: Build node
        uses: docker/build-push-action@v2
        with:
          context: node
          platforms: linux/amd64
          push: true
          tags: |
            fangedhex/devcontainers:node
      - name: Build java
        uses: docker/build-push-action@v2
        with:
          context: java
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            fangedhex/devcontainers:java
